### PR TITLE
Migrate home page to React components

### PR DESCRIPTION
**Pull request by antsgar**
Shared header, shared footer and usage view updated to render React components. Upcoming PRs for the rest of the pages but I think it may be easier to review gradual updates. All views should render without visible changes to the user and the application should still run in the same way as it did before. Feedback is very welcome!

### CODE REVIEW

**Comment by atmoio** [comment]
Nice work! Works great locally. I've talked to @karolsojko about how we can set up deployment for this in a dev environment so we'll wait on him to see how we should handle staging this.

**Comment by karolsojko** [comment]
Hey guys,

let’s rebase this to `develop`, merge it there if it looks good.
We can work from there in terms of fixes/adjustments until it looks good on dev env 😊 I will take care of adjusting the builds and deployments once merged to `develop`

**Comment by atmoio** [comment]
@antsgar can you add instructions in the README on how to set up locally?

Also target the develop branch instead of master for this PR. You might have to create a new PR but I'm not sure.

**Comment by atmoio** [comment]
I've changed the target branch. Here are instructions from @karolsojko on how to rebase:

```markdown
# make sure we got everything up to date
git fetch origin -p 
# checkout that PR branch and make sure it is up to date
git checkout react-migration && git pull origin react-migration
# rebase
git pull --rebase origin develop
# this will probably cause some conflicts - but not necesarilly - if it does they will have to be resolved and git rebase —continue will have to be applied afterwards
# once everything is ok (force because we are rewritting history of this branch aka rebase):
git push -f origin react-migration 
```

So this and the readme and we should be good to go 👍

**Review by atmoio — APPROVED** [review]

**Comment by karolsojko** [comment]
Closing this one in favor of https://github.com/standardnotes/listed/pull/34

@antsgar if you could make another PR with the `README` update that would be great 👍

**Comment by antsgar** [comment]
@mobitar apologies, for some reason my e-mail notifications from GitHub got disabled. Will update readme in upcoming PR, @karolsojko thanks for taking care of rebasing for me!

**Pull request closed without merging**
