### PR TITLE
Migrate author and post page and enable Turbolinks

### PR DESCRIPTION
**Pull request by antsgar**
- Author page migrated to React
- Post page (rendered when clicking on one of the author's posts) migrated to React, including component for subscription to author's posts
- Support for printing debug messages for Turbolinks in dev environment wasn't configured properly. Fixed that and noticed it wasn't recognising Turbolinks as installed. Installed with yarn instead of gem and it now correctly prints the debug message saying it's using Turbolinks. Maybe this will fix our slow author page rendering issue?

### CODE REVIEW

**Comment by atmoio** [comment]
Hey @antsgar, excited to review this! I'm a little backed up currently and hope to get a chance to review this by the end of the week.

**Comment by antsgar** [comment]
Hi @mobitar! Awesome :) just added a fix to a mistake I noticed in the turbolinks setup.

**Comment by antsgar** [comment]
@mobitar updated with migration of Subscribe, Thank and Guestbook pages. Might be too big a PR to review, if that's the case just let me know and I can remove the commits and add them to a follow-up PR later on. Thanks!!

**Comment by atmoio** [comment]
I noticed on the post page when you inspect the source of the page, you see that all texts of all the post is rendered in the source, after "More from author" is complete.

It looks like this:

```
   <script type="application/json" class="js-react-on-rails-component" data-component-name="PostShow" data-trace="true" data-dom-id="PostShow-react-component-2cafa7e8-ce07-4216-b178-df8f54d338e6">{"post":{"id":11537,"token":"4kM5FzP3Cz","item_uuid":"ecc5e343-a7c4-4ea7-81df-c9dae188f7ce","title":"Simulation overflow","text": "..."
```

And then it lists all the author's posts and their full text.

**Comment by atmoio** [comment]
I'm not able to get captchas working. When you submit the subscribe form, it should create a new database entry in the `simple_captcha_data` table. This is not happening on this branch (but works on master). Because of this, notice you will see a 404 after submitting your email address to subscribe:

404 http://localhost:3009/simple_captcha?code=976261f28663d45fc0a1eb17a9e3e83de78428e0&time=1594743471

**Comment by antsgar** [comment]
@mobitar good catch! Updated with a couple of commits:

- Used :only option for as_json when passing properties to React components, to only pass the attributes needed for rendering and not the entire models
- Fixed the captcha issue, calling show_simple_captcha method from SimpleCaptcha controller was needed to generate the record in the database

**Comment by atmoio** [comment]
Great, issues fixed 👍

One other issue I'm seeing: when you go on an author's page, then refresh the page in the browser, you will see this in the console:

```
 Each child in a list should have a unique "key" prop. (in div (at Show.jsx:9))
```

**Comment by antsgar** [comment]
@mobitar should be fixed now :) will keep working on other pages but will wait til this PR is closed to open another one, so changes don't pile up. Let me know if you notice any other issues! Thanks for reviewing

**Review by atmoio — APPROVED** [review]

**Comment by atmoio** [comment]
Btw be sure to create different branch names for every PR as to avoid confusion :)

**Pull request merged**
