### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by antsgar**
Listed redesign implementation.

### CODE REVIEW

**Review by atmoio — APPROVED** [review]

**Comment by antsgar** [comment]
@mobitar merged to develop but seeing a "Something went wrong" message in the dev environment. @karolsojko perhaps you could help me find out what went wrong? Thanks!

Just in case we need more time to figure out what happened, I've opened a rollback PR to keep a stable develop branch in case anyone else needs to make other changes.

**Comment by karolsojko** [comment]
@antsgar I've fixed the initial issue which was there - mainly when there were no active authors the `easter_egg_index` was null so you couldn't insert the easter egg author to the array: https://github.com/standardnotes/listed/commit/de9ab0df743ba87010290547f1020b34cb746899

But now there is an issue with React on pre-rendering. I'm sure you'll have more experience in fixing this. The output in logs is something like this:
```
....
app_1  | ActionView::Template::Error (ERROR in SERVER PRERENDERING
app_1  | Encountered error: "ReferenceError: document is not defined"
app_1  | when prerendering Usage with props: {"activeAuthors":[{"id":"easter-egg","featured":false,"bio":"Share your experience in its truest form. Start writing now.","title":"This could be you :)"}]}
app_1  | 
app_1  | code:
app_1  | 
app_1  |         (function() {
app_1  |           var railsContext = {"railsEnv":"production","inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","rorVersion":"11.3.0","rorPro":false,"href":"http://localhost:3000/","location":"/","scheme":"http","host":"localhost","port":3000,"pathname":"/","search":null,"httpAcceptLanguage":"pl-pl","serverSide":true};
app_1  |               ReactOnRails.clearHydratedStores();
app_1  | 
app_1  |           var props = {"activeAuthors":[{"id":"easter-egg","featured":false,"bio":"Share your experience in its truest form. Start writing now.","title":"This could be you :)"}]};
app_1  |           return ReactOnRails.serverRenderReactComponent({
app_1  |             name: 'Usage',
app_1  |             domNodeId: 'Usage-react-component-5b8444a6-3e5a-421b-a9dd-f168fd7687c0',
app_1  |             props: props,
app_1  |             trace: false,
app_1  |             railsContext: railsContext
app_1  |           });
app_1  |         })()
app_1  | 
app_1  | 
app_1  | 
app_1  | c ((execjs):37:60676)
app_1  | _ ((execjs):37:61930)
app_1  | l ((execjs):37:60615)
app_1  | e.exports ((execjs):37:62263)
app_1  | Object.(execjs) (<anonymous>:37:579628)
app_1  | t ((execjs):37:110)
app_1  | Module.(execjs) (<anonymous>:37:805323)
app_1  | t ((execjs):37:110)
app_1  | (execjs):37:911
app_1  | (execjs):37:922
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:209:in `eval_unsafe'
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:209:in `block (2 levels) in eval'
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:329:in `timeout'
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:208:in `block in eval'
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:206:in `synchronize'
app_1  | /usr/local/bundle/gems/mini_racer-0.2.14/lib/mini_racer.rb:206:in `eval'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:10:in `block in initialize'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:66:in `translate'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:9:in `initialize'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
app_1  | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb:140:in `create_js_context'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb:16:in `block in reset_pool'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:171:in `try_create'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:83:in `block (2 levels) in pop'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `loop'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `block in pop'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `synchronize'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `pop'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:93:in `checkout'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:62:in `block in with'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
app_1  | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb:99:in `eval_js'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb:57:in `exec_server_render_js'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/server_rendering_pool.rb:22:in `server_render_js_with_console_logging'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/helper.rb:504:in `server_rendered_react_component'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/helper.rb:445:in `internal_react_component'
app_1  | /usr/local/bundle/gems/react_on_rails-11.3.0/lib/react_on_rails/helper.rb:103:in `react_component'
app_1  | /listed/app/views/usage/index.html.erb:1:in `_app_views_usage_index_html_erb__4094607537854886825_47069169114840'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/template.rb:159:in `block in render'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/template.rb:354:in `instrument'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/template.rb:157:in `render'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/template_renderer.rb:14:in `render'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/renderer.rb:42:in `render_template'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/renderer/renderer.rb:23:in `render'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/rendering.rb:104:in `_render_template'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/rendering.rb:83:in `render_to_body'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/abstract_controller/rendering.rb:26:in `render'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/rendering.rb:36:in `render'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
app_1  | /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
app_1  | /usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/implicit_render.rb:36:in `default_render'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:188:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:126:in `call'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:455:in `call'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `block in instrument'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `instrument'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
app_1  | /usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:126:in `process'
app_1  | /usr/local/bundle/gems/actionview-5.0.7.2/lib/action_view/rendering.rb:30:in `process'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:190:in `dispatch'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:262:in `dispatch'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `each'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `serve'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:727:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
app_1  | /usr/local/bundle/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
app_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `block in call'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:26:in `tagged'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `tagged'
app_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `call'
app_1  | /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
app_1  | /usr/local/bundle/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
app_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:136:in `call'
app_1  | /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
app_1  | /usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
app_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:522:in `call'
app_1  | /usr/local/bundle/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
app_1  | /usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
app_1  | /usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
app_1  | /usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
app_1  | /usr/local/bundle/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'):
app_1  |     1: <%= react_component("Usage", props: {
app_1  |     2:     activeAuthors: @active_authors.as_json(
app_1  |     3:         only: [:id, :featured, :bio, :title],
app_1  |     4:         methods: [:url, :title, :word_count]
app_1  |   
app_1  | app/views/usage/index.html.erb:1:in `_app_views_usage_index_html_erb__4094607537854886825_47069169114840'
```

To reproduce this just checkout the latest develop and do:
```
docker-compose up
```

after you see `Starting server...` wait a second or two and open up localhost:3000 - let me know if you have any problems

**Comment by karolsojko** [comment]
Maybe this could be a clue: https://github.com/reactjs/react-rails/issues/319

**Comment by antsgar** [comment]
@karolsojko thank you! That makes sense, although I wonder why there weren’t any active authors? We did have some featured authors in the dev database. I’ll check this new error today and let you know how it goes

**Comment by antsgar** [comment]
@karolsojko I've been trying to reproduce this error on Wednesday and today but so far no luck, locally even with docker compose I get the app up and running correctly. Are you seeing the same error when running locally? Are there any other logs that could help? Thanks!!

**Comment by atmoio** [comment]
@antsgar I've DM'd you

**Pull request merged**
